version: "3.8"
services:
  digipoort:
    image: ebms-adapter-digipoort:2.17.3
    ports:
      - "8080:8080"
  overheid:
    image: ebms-adapter-overheid:2.17.3
    ports:
      - "8000:8000"
      - "61616:61616"
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres:12
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_USER: ebms
      POSTGRES_PASSWORD: ebms
      POSTGRES_DB: ebms
