services:
  digipoort-postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ebms
      POSTGRES_PASSWORD: ebms
      POSTGRES_DB: ebms
  digipoort:
    image: eluinstra/ebms-adapter-pg:2.19
    depends_on:
      - digipoort-postgres
    environment:
      https_verifyHostnames: "true"
      ebms_jdbc_update: "true"
      ebms_jdbc_url: "jdbc:postgresql://digipoort-postgres:5432/ebms"
      ebms_jdbc_username: "ebms"
      ebms_jdbc_password: "ebms"
    entrypoint: ["./start.sh","-soap"]
    expose:
      - 8080
      - 8888
    ports:
      - "8080:8080"
  overheid:
    image: eluinstra/ebms-adapter-pg:2.19
    environment:
      https_verifyHostnames: "true"
      cache_type: "IGNITE"
      transactionManager_type: "ATOMIKOS"
      deliveryTaskHandler_type: "JMS"
      deliveryManager_type: "JMS"
      eventListener_type: "JMS"
      jms_brokerURL: "tcp://activemq:61616"
      ebms_jdbc_update: "true"
      ebms_jdbc_driverClassName: org.postgresql.xa.PGXADataSource
      ebms_jdbc_url: "jdbc:postgresql://postgres:5432/ebms"
      ebms_jdbc_username: "ebms"
      ebms_jdbc_password: "ebms"
      ebms_pool_minPoolSize: "4"
      ebms_pool_maxPoolSize: "4"
    entrypoint: ["./start.sh","-headless","-disableEbMSClient"]
    expose:
      - 8888
    depends_on:
      - activemq
      - postgres
  client:
    image: eluinstra/ebms-adapter-pg:2.19
    environment:
      https_verifyHostnames: "true"
      cache_type: "IGNITE"
      transactionManager_type: "ATOMIKOS"
      deliveryTaskHandler_type: "JMS"
      deliveryManager_type: "JMS"
      eventListener_type: "JMS"
      jms_brokerURL: "tcp://activemq:61616"
      ebms_jdbc_update: "true"
      ebms_jdbc_driverClassName: org.postgresql.xa.PGXADataSource
      ebms_jdbc_url: "jdbc:postgresql://postgres:5432/ebms"
      ebms_jdbc_username: "ebms"
      ebms_jdbc_password: "ebms"
      ebms_pool_minPoolSize: "4"
      ebms_pool_maxPoolSize: "4"
    entrypoint: ["./start.sh","-headless","-disableEbMSServer"]
    depends_on:
      - activemq
      - postgres
  api:
    image: eluinstra/ebms-adapter-pg:2.19
    environment:
      https_verifyHostnames: "true"
      cache_type: "IGNITE"
      transactionManager_type: "ATOMIKOS"
      deliveryTaskHandler_type: "JMS"
      deliveryManager_type: "JMS"
      eventListener_type: "JMS"
      jms_brokerURL: "tcp://activemq:61616"
      ebms_jdbc_update: "true"
      ebms_jdbc_driverClassName: org.postgresql.xa.PGXADataSource
      ebms_jdbc_url: "jdbc:postgresql://postgres:5432/ebms"
      ebms_jdbc_username: "ebms"
      ebms_jdbc_password: "ebms"
      ebms_pool_minPoolSize: "4"
      ebms_pool_maxPoolSize: "4"
    entrypoint: ["./start.sh","-ssl","-soap","-disableEbMSServer","-disableEbMSClient"]
    expose:
      - 8443
    ports:
      - "8000:8443"
    depends_on:
      - activemq
      - postgres
  activemq:
    image: apache/activemq-classic:5.18.4
    ports:
      - "8161:8161"
      # - "61616:61616"
    # volumes:
    #   - ./data:/opt/apache-activemq/data
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ebms
      POSTGRES_PASSWORD: ebms
      POSTGRES_DB: ebms
    # ports:
    #   - "5432:5432"
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf:ro
      # - ./data:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
