services:
  digipoort-postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ebms
      POSTGRES_PASSWORD: ebms
      POSTGRES_DB: ebms
  digipoort:
    image: eluinstra/ebms-adapter-pg:2.19
    depends_on:
      - digipoort-postgres
    environment:
      https_verifyHostnames: "true"
      ebms_jdbc_update: "true"
      ebms_jdbc_url: "jdbc:postgresql://digipoort-postgres:5432/ebms"
      ebms_jdbc_username: "ebms"
      ebms_jdbc_password: "ebms"
    entrypoint: ["./start.sh","-soap"]
    expose:
      - 8080
      - 8888
    ports:
      - "8080:8080"
  overheid:
    image: eluinstra/ebms-adapter-pg:2.19
    environment:
      https_verifyHostnames: "true"
      jms_broker_start: "true"
      eventListener_type: "JMS"
      ebms_jdbc_update: "true"
      ebms_jdbc_url: "jdbc:postgresql://postgres:5432/ebms"
      ebms_jdbc_username: "ebms"
      ebms_jdbc_password: "ebms"
    entrypoint: ["./start.sh","-ssl","-soap"]
    expose:
      - 8443
      - 8888
    ports:
      - "8000:8443"
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ebms
      POSTGRES_PASSWORD: ebms
      POSTGRES_DB: ebms
    # ports:
    #   - "5432:5432"
    # volumes:
    #   - ./data:/var/lib/postgresql/data
