services:
  digipoort:
    image: eluinstra/ebms-adapter-bin:${EBMS_VERSION}
    environment:
      ebms_verifyHostnames: "false"
      https_verifyHostnames: "false"
      ebms_jdbc_update: "true"
    command: "./start.sh -h2 -soap"
    expose:
      - 8080
      - 8888
    ports:
      - "8080:8080"
  overheid:
    image: eluinstra/ebms-adapter-pg:${EBMS_VERSION}
    environment:
      ebms_verifyHostnames: "false"
      https_verifyHostnames: "false"
      cache_type: "DEFAULT"
      jms_broker_start: "true"
      eventListener_type: "JMS"
      ebms_jdbc_update: "true"
      ebms_jdbc_url: "jdbc:postgresql://postgres:5432/ebms"
      ebms_jdbc_username: "ebms"
      ebms_jdbc_password: "ebms"
    command: "./start.sh -ssl -soap"
    expose:
      - 8443
      - 8888
    ports:
      - "8000:8443"
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ebms
      POSTGRES_PASSWORD: ebms
      POSTGRES_DB: ebms
    # ports:
    #   - "5432:5432"
    # volumes:
    #   - ./data:/var/lib/postgresql/data
