version: "3.8"
services:
  digipoort:
    image: eluinstra/ebms-adapter-digipoort:latest
    ports:
      - "8080:8080"
  overheid:
    image: eluinstra/ebms-adapter-overheid:latest
    ports:
      - "8000:8080"
