services:
  digipoort:
    image: eluinstra/ebms-adapter-bin:${EBMS_VERSION}
    environment:
      https_verifyHostnames: "false"
      ebms_jdbc_update: "true"
    command: "./start.sh -h2 -soap"
    expose:
      - 8080
      - 8888
    ports:
      - "8080:8080"
  # digipoort_init:
  #   image: busybox:latest
  #   depends_on:
  #     - digipoort
  #   environment:
  #     CPA_FILE: cpa.xml
  #   entrypoint: ["sh", "-c"]
  #   command: |
  #     curl -L https://github.com/eluinstra/ebms-docker/blob/2.19.x/examples/cpa.xml -o $CPA_FILE
  #     curl -X POST -H "Content-Type: text/plain" --data @${CPA_FILE} http://digipoort:8080/service/rest/v19/cpas?overwrite=true
  overheid:
    image: eluinstra/ebms-adapter-bin:${EBMS_VERSION}
    environment:
      https_verifyHostnames: "false"
      ebms_jdbc_update: "true"
    command: "./start.sh -h2 -soap"
    expose:
      - 8080
      - 8888
    ports:
      - "8000:8080"
