services:
  digipoort:
    image: eluinstra/ebms-adapter-bin:2.18.11
    environment:
      https_verifyHostnames: "false"
      ebms_jdbc_update: "true"
    entrypoint: ["./start.sh","-hsqldb","-soap"]
    expose:
      - 8080
      - 8888
    ports:
      - "8080:8080"
  overheid:
    image: eluinstra/ebms-adapter-bin:2.18.11
    environment:
      https_verifyHostnames: "false"
      ebms_jdbc_update: "true"
    entrypoint: ["./start.sh","-hsqldb","-soap"]
    expose:
      - 8080
      - 8888
    ports:
      - "8000:8080"
